### ISSUE TITLE
crash after click to geo: link uri

### ISSUE THREAD

**Issue by Karry** [sailfishos/sailfish-browser#1012]
Hi. With recent SFOS upgrade (4.5.0.16), sailfish browser is crashing when trying to open geo: uri. Like this one: `geo:37.786971,-122.399677` on Wikipedia page https://en.wikipedia.org/wiki/Geo_URI_scheme . I am sure that it was working fine in previous SFOS release...

**Comment by pvuorela** [comment]
Works fine for me.

**Comment by Karry** [comment]
```
Thread 10 "GeckoWorkerThre" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fa597d990 (LWP 29294)]
WindowCreator::CreateChromeWindow (this=this@entry=0x7eb0003370, aParent=aParent@entry=0x0, 
    aChromeFlags=<optimized out>, aChromeFlags@entry=2281702926, aOpenWindowInfo=aOpenWindowInfo@entry=0x0, 
    aCancel=aCancel@entry=0x7fa597afaf, _retval=0x7fa597afb0)
    at /usr/src/debug/xulrunner-qt5-78.15.1+git33-1.19.1.jolla.aarch64/mobile/sailfishos/utils/WindowCreator.cpp:58
58        RefPtr<BrowsingContext> parentBrowsingContext = aOpenWindowInfo->GetParent();
```
top of `bt full`:
```
#0  WindowCreator::CreateChromeWindow (this=this@entry=0x7eb0003370, aParent=aParent@entry=0x0, 
    aChromeFlags=<optimized out>, aChromeFlags@entry=2281702926, aOpenWindowInfo=aOpenWindowInfo@entry=0x0, 
    aCancel=aCancel@entry=0x7fa597afaf, _retval=0x7fa597afb0)
    at /usr/src/debug/xulrunner-qt5-78.15.1+git33-1.19.1.jolla.aarch64/mobile/sailfishos/utils/WindowCreator.cpp:58
        parent = <optimized out>
        createdID = 0
        parentID = 127
        parentBrowsingContext = <optimized out>
        __PRETTY_FUNCTION__ = "virtual nsresult WindowCreator::CreateChromeWindow(nsIWebBrowserChrome*, uint32_t, nsIOpenWindowInfo*, bool*, nsIWebBrowserChrome**)"
        rv = <optimized out>
        browser = {<nsCOMPtr_base> = {
            mRawPtr = 0x7fbca24a7c <nsWindowWatcher::CreateChromeWindow(nsIWebBrowserChrome*, unsigned int, nsIOpenWindowInfo*, nsIWebBrowserChrome**)+84>}, <No data fields>}
        thread = {<nsCOMPtr_base> = {mRawPtr = 0x7fbfa1f000}, <No data fields>}
#1  0x0000007fbca24a98 in nsWindowWatcher::CreateChromeWindow (this=this@entry=0x7ebc02e400, 
    aParentChrome=aParentChrome@entry=0x0, aChromeFlags=aChromeFlags@entry=2281702926, 
    aOpenWindowInfo=aOpenWindowInfo@entry=0x0, aResult=0x7fa597b118)
    at /home/abuild/rpmbuild/BUILD/xulrunner-qt5-78.15.1+git33/obj-build-mer-qt-xr/dist/include/nsCOMPtr.h:1351
        cancel = false
        newWindowChrome = {<nsCOMPtr_base> = {mRawPtr = 0x0}, <No data fields>}
        rv = <optimized out>
#2  0x0000007fbca2c478 in nsWindowWatcher::OpenWindowInternal (this=this@entry=0x7ebc02e400, aParent=aParent@entry=0x0, 
    aUrl=<optimized out>, aName=<optimized out>, aFeatures=<optimized out>, aCalledFromJS=aCalledFromJS@entry=false, 
    aDialog=<optimized out>, aNavigate=aNavigate@entry=true, aArgv=aArgv@entry=0x7f8227d340, 
    aIsPopupSpam=aIsPopupSpam@entry=false, aForceNoOpener=aForceNoOpener@entry=false, 
```
full bt: [stacktrace.log](https://github.com/sailfishos/sailfish-browser/files/10662304/stacktrace.log)

**Comment by jovirkku** [comment]
Opening the Wikipedia page https://en.wikipedia.org/wiki/Geo_URI_scheme with the Sailfish Browser of Xperia 10 III (4.5.0.16) works for me, too.

**Comment by Karry** [comment]
Oh, sorry for confusion, the Wikipedia page itself is not the problem. But the geo link in "Example" section is. Github markdown don't allow me to create clickable geo link here in description...

**Comment by jovirkku** [comment]
I have the apps Sailfish Maps and OsmAnd+ installed. When clicking that geo link Sailfish offers those apps to use. Both of them take me to San Francisco. And the browser keeps working.
But I heard soon after that this is the case where there are no apps with geo URI enabled...  I could not see this because of those apps.

**Comment by Karry** [comment]
This is weird. I definitely have map applications, that are able to handle geo links. Like OSM Scout (native), Mapy.cz, HERE WeGo...

**Comment by Karry** [comment]
I am not able to reproduce the crash after reflashing my phone.
